language: scala
sudo: false
jdk: oraclejdk8
rvm:
  - 2.5.0
node_js:
  - 8.4.0

before_script:
  - bundle install
  - npm install -g gulp-cli gulp bower

cache:
  directories:
  - $HOME/.m2
  - $HOME/.ivy2
  - $HOME/.sbt/boot/scala-$TRAVIS_SCALA_VERSION
  - $HOME/.sbt/launchers
  - samples/play-gulp-react/ui/node_modules

before_cache:
  - rm -rf $HOME/.ivy2/local/com.github.mmizutani/*
  - find $HOME/.ivy2 -name "ivydata-*.properties" -delete
  - find $HOME/.sbt -name "*.lock" -delete

matrix:
  include:
  - env: SBT_VERSION="0.13.16"
    jdk: oraclejdk8
  - env: SBT_VERSION="1.1.1"
    jdk: oraclejdk8

script:
  - sbt "^^${SBT_VERSION}" test scripted
  - cd samples/play-gulp-react/ui && npm install
  - cd ../ && sbt ";clean;compile;test"

notifications:
  slack:
    secure: ns8d1pHpl41hAj9or4m9XSYZf5ht5I5hNzRbtC2DhEeB65NTNwld6+S1OG5hntKyXlJXTtnj+yFcX15Ok29ApdaLH9UiAl30RROsWc2GpOt3LaMf09foEKCM/5I53PR7GuKpSz3AO0O0xBb0/6GAiKv6YaMXvfrzoXumHGRTQ79vrEvT6dHdTO4h3Y2uiO2Ou9nziMxmtJNRQv4SGy/dw89+8njqOQ1EwQJsZTTSyek0JVeavDdinQUhRlQFrpVagU+oIv8sKJKV1o/75VKSlufhGX0fSIyu7//u9ImiWCsHSG2wbDE2vLALKiRCktErULeyncZZY30ZWY1cW1qcmwiTs5h8mfaq+oNmhwzHjanzhTLSFvAj7ECIMMhFF2sYSdftFY0hQ2E9ThBcE964i6pFLiF+ZiKSUXwxaUNF3tRVgMGOMy49/fsjhG2qZT/IQ1lNORhibV1ru9BBUFOjuZLisuk//7p6N47fIEwZazx8J6z7VMC9+Rjk89+tORFczK9dW0BAElUmZG3FYGCxIpAbVaDCi5GzxIJdpZoQRgWn2x2yubxuqE+FCGaonxsPJSZhtOF+M7iY+vYOzDHR57gM45GMsSgjUlVEFbqAqy8YDrFnHYRcDrUWint11cfRBnf03ucBXnaqa+A/WxVssy7GODOuoc1Q6VSkkg4SR9k=
